name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Ensure correct working directory
        run: |
          echo "Working directory at start: $(pwd)"
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          cd $GITHUB_WORKSPACE  # Asegura que estés en la raíz
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pytest

      - name: Run tests
        run: |
          pytest
